chrace/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('racers/', include('racers.urls')),
    path('tourneys/', include('tourneys.urls')),
    path('admin/', admin.site.urls),
]

tourneys/urls.py
from django.urls import path

from . import views

app_name = 'tourneyz'
urlpatterns = [
   path('', views.IndexView.as_view(), name='index'),
   path('<int:pk>/races/', views.RaceView.as_view(), name='races'),
   path('<int:pk>/', views.edit, name='edit'),
   path('<int:pk>/go', views.run, name='run'),
   path('race_result', views.race_result, name='race_result'),
]

tourneys/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import transaction
from datetime import datetime
from operator import itemgetter

# this represents a set of races and register cars
class Tournament(models.Model):
   # the date of the tournament
   date = models.DateField()
   
   # the registered cars for the tournament
   registered_cars = models.ManyToManyField('racers.RaceCar', through='Registration')
   
   # only one tournament can be active at a time
   active = models.BooleanField(default=False)

   # the pretty print string for this object   
   def __str__(self):
      return f'Tournament {self.id} on {self.date}'
   
   # sets this tournament as active
   @transaction.atomic
   def activate(self):
      if not self.active:
         self.active = True
         return True
      return False

   # sets this tournament as inactive
   @transaction.atomic
   def deactivate(self):
      if self.active:
         self.active = False
         return True
      return False

   # find the right car
   def car_index(self, cars, car):
      for i, c in enumerate(cars):
         if c[0].id == car.id:
            return i
      return -1
   
   # gets the results of this tournament
   def results(self):
      races = Race.objects.filter(tourney_id=self.id)
      reg_cars = self.registered_cars.all()
      car_results = []
      for c in reg_cars:
         car_results.append([c, 0, 0])
      for r in races:
         for t in r.trials:
            #[ (car, et, cnt) for car, et, count in cars if car.id  == t.car.id ]
            index = self.car_index(car_results, t.car)
            if index > -1:
               car_results[index][1] += t.et()
               car_results[index][2] += 1
      car_ets = []
      for c in car_results:
         car_ets.append([c[0], c[1]/c[2] if c[2] > 0 else 1000])
      return sorted(car_ets, key=itemgetter(1))

# a single car and the tournament it participates in
class Registration(models.Model):
   tourney = models.ForeignKey(Tournament, on_delete=models.CASCADE)
   car = models.ForeignKey('racers.RaceCar', on_delete=models.CASCADE)

   def __str__(self):
      return f'{self.car} part of {self.tourney}'

# four cars go down the track, 1 winner is a fact
class Race(models.Model):
   tourney = models.ForeignKey(Tournament, on_delete=models.CASCADE)
   start_time = models.BigIntegerField(default=0)
   racers = models.ManyToManyField('racers.RaceCar', through='TimeTrial', related_name='races')
   
   # pretty print this object
   def __str__(self):
      return f'Race {self.id} from {self.tourney}'
      
   # set the time for all lanes of a race
   def set_lane_times(self, times):
      print(f'setting lane times {times}')
      trials = TimeTrial.objects.filter(race_id=self.id).order_by('lane')
      for i, t in enumerate(trials):
         if i < len(times):
            t.end_time = times[i]
            t.save() 
      return

   # set the time for a given lane of this race
   def set_lane_time(self, lane, time):
      trials = TimeTrial.objects.filter(race_id=self.id)
      for t in trials:
         if t.lane == lane:
            t.end_time = time
      return

   # get the start time as a time
   @property
   def time_of_start(self):
      if self.start_time == 0:
         return '?'
      else:
         return timezone.make_aware(datetime.fromtimestamp(self.start_time / (1e9))).time()
   
   # get an elapsed time since the start of the race
   @property
   def et(self):
      if self.start_time:
         return (timezone.now() - self.start_time)
      return -1

   @property
   def trials(self):
      trials = TimeTrial.objects.filter(race_id=self.id).order_by('lane')
      if len(trials) == 4:
         if trials[0].end_time and trials[1].end_time and trials[2].end_time and trials[3].end_time:
            return TimeTrial.objects.filter(race_id=self.id).order_by('end_time')
      return trials

   @property
   def racers_by_lane(self):
      return self.racers.order_by('timetrial__lane')

# a single car and it's time in a single race
class TimeTrial(models.Model):
   MAX_LANES = 4
   race = models.ForeignKey(Race, on_delete=models.CASCADE)
   car = models.ForeignKey('racers.RaceCar', on_delete=models.CASCADE)
   lane = models.IntegerField(validators=[
                                 MaxValueValidator(MAX_LANES),
                                 MinValueValidator(1)
                              ])
   #rank = models.IntegerField(validators=[
   #                              MaxValueValidator(MAX_LANES),
   #                              MinValueValidator(1)
   #                           ])
   mid_time = models.BigIntegerField(default=0)
   end_time = models.BigIntegerField(default=0)
   
   # get the average miles per hour
   def mph(self):
      ftpersec = 40 / self.et()
      return ftpersec * 0.681818
   
   # get the elapsed time at the finish line
   def et(self):
      delta = self.end_time - self.race.start_time
      return delta / 1e9
   
   # pretty print this object
   def __str__(self):
      et = self.et()
      if et > 0:
         return f'[{self.car.id}]{self.car} with ET: {et:.3f}'
      return f'Lane {self.lane}: [{self.car.id}]{self.car}'

tourneys/views.py
from django.shortcuts import get_object_or_404,render
from .models import Race,Tournament,Registration,TimeTrial
from django.http import HttpResponseRedirect, HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
import logging
from django.views.decorators.http import require_http_methods
from django.apps import apps
from django.utils import timezone
from collections import deque
import json

MAX_LANES = 4

class IndexView(generic.ListView):
   template_name = 'tourneys/index.html'
   context_object_name = 'all'

   def get_queryset(self):
      return Tournament.objects.filter(
         date__lte=timezone.now()
      ).order_by('-date')[:5]

class RaceView(generic.DetailView):
   model = Race
   template_name = 'tourneys/races.html'

@require_http_methods(["GET", "POST"])
def edit(request, pk):
   tourney = get_object_or_404(Tournament, pk=pk)
   my_cars = tourney.registered_cars.all()

   my_cars_ids = []
   for c in my_cars:
      my_cars_ids.append(c.id)

   RaceCar = apps.get_model('racers', 'RaceCar')
   other_cars = RaceCar.objects.exclude(pk__in=my_cars_ids)

   context = {
      'tourney' : tourney,
      'other_cars': other_cars,
      'my_cars' : my_cars,
   }

   return render(request, 'tourneys/edit.html', context)

@require_http_methods(["GET", "POST"])
def run(request, pk):
   tourney = get_object_or_404(Tournament, pk=pk)
   my_cars = tourney.registered_cars.all()
   my_races = Race.objects.filter(tourney_id=tourney.id).order_by('id')
   live_race = next_race = tourney_results = None
   
   if request.method == 'POST' and not my_races:
      # create new races based on registered cars
      print('creating new races')
      lanes = [ deque(), deque(), deque(), deque() ]
      for c in my_cars:
         for a in lanes:
            a.append(c)
      for i,a in enumerate(lanes):
         while len(a) < MAX_LANES:
            a.append(None)
         a.rotate(i)
      print(lanes)
      while len(lanes[0]) > 0 or len(lanes[1]) > 0 or len(lanes[2]) > 0 or len(lanes[3]) > 0:
         race = Race.objects.create(tourney=tourney)
         for i,a in enumerate(lanes):
            if len(a) > 0:
               if a[0]:
                  TimeTrial.objects.create(race=race,car=a[0],lane=i+1)
               a.popleft()
      my_races = Race.objects.filter(tourney_id=tourney.id).order_by('id')

   if request.GET.get('startracebtn') and request.GET.get('raceid'):
      # get ready to rumble
      raceid = request.GET.get('raceid')
      live_race = int(raceid)
      print(f'Starting Race {raceid}')
      import os
      os.system(f'python3 /home/pi/chrace/gpio.py {raceid} &')
   else:
       for r in my_races:
          if not r.start_time:
             next_race = r.id
             break

   if not next_race:
      tourney_results = tourney.results()
   
   context = {
      'tourney' : tourney,
      'my_cars' : my_cars,
      'my_races' : my_races,
      'live_race' : live_race,
      'next_race' : next_race,
      'results' : tourney_results
   }

   return render(request, 'tourneys/run.html', context)

def race_result(request):
   # request.is_ajax() is deprecated since django 3.1
   is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
   print(f'is ajax {is_ajax}')
   if is_ajax:
      if request.method == 'POST':
         data = json.load(request)
         raceid = data.get('raceid')
         race = get_object_or_404(Race, pk=raceid)
         trials = TimeTrial.objects.filter(race_id=race.id).order_by('lane')
         context = {
            'start_time' : race.start_time,
            #'lane1' : trials[0].et() if len(trials) > 0 else 0,
            #'lane2' : trials[1].et() if len(trials) > 1 else 0,
            #'lane3' : trials[2].et() if len(trials) > 2 else 0,
            #'lane4' : trials[3].et() if len(trials) > 3 else 0,
         }
         return JsonResponse(context)
      return JsonResponse({'status': 'Invalid request'}, status=400)
   else:
      return HttpResponseBadRequest('Invalid request')

tourneys/templates/tourneys/edit.html
<h1>Tournament {{tourney.id}}</h1>
<p>This Tournament is held on {{ tourney.date }}.<p>

<form action="{% url 'tourneyz:run' tourney.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Cars for {{tourney}}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for car in my_cars %}
        <input type="radio" name="incar" id="incar{{ forloop.counter }}" value="{{ car.id }}">
        <label for="incar{{ forloop.counter }}">{{ car }}</label><br>
    {% endfor %}
</fieldset>
{% if other_cars %}
<fieldset>
    <legend><h1>Other Cars</h1></legend>
    {% for car in other_cars %}
       <input type="radio" name="outcar" id="outcar{{ forloop.counter }}" value="{{ car.id }}"> 
       <label for="outcar{{ forloop.counter }}">{{ car }}</label><br>
    {% endfor %}
</fieldset>
{% endif %}
<input type="submit" value="Start">
</form>

tourneys/templates/tourneys/index.html
{% load static %}

<!--<link rel="stylesheet" type="text/css" href="{% static 'tourneys/style.css' %}">-->

<h1>GBC Pinewood Derby Tournaments</h1>

{% if all %}
    <ul>
    {% for tourney in all %}
        <li><a href="{% url 'tourneyz:edit' tourney.id %}">{{tourney}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Show all Tournaments here.</p>
{% endif %}

tourneys/templates/tourneys/races.html
Races {{ object }}

tourneys/templates/tourneys/run.html
<h1>Tournament {{tourney.id}}</h1>
<p>This Tournament is held on {{ tourney.date }}.<p>

{% load tz %}

{% if my_cars %}
<h2>Participating Cars</h2>
{% if not next_race and results %}
<script>
function showResults() {
  var x = document.getElementById("resultsdiv");
  if (x.style.display === "none") {
    x.style.display = "block";
    document.getElementById("resultsBtn").innerHTML = "Hide Results";
  } else {
    x.style.display = "none";
    document.getElementById("resultsBtn").innerHTML = "Show Results";
  }
}
</script>
<button id="resultsBtn" onclick="showResults()">Show Results</button>
<div id="resultsdiv" style="display: none">
<ol>
   {% for c in results %}
      <li>
      <p>{{ c.0 }} with average Elapsed Time of {{ c.1 }} seconds.</p>
      {% if forloop.counter < 4 %}
      <p>Congratulations {{c.0.driver.first_name.capitalize}}!</p>
      {% endif %}
      </li>
   {% endfor %}
</ol>
</div>
{% else %}
<ul>
   {% for c in my_cars %}
      <li>{{ c }}</li>
   {% endfor %}
</ul>
{% endif %}

{% if my_races %}
<h2>Races</h2>
    <ul>
    {% for r in my_races %}
        <li>
           <div style="display: flex;">
              <p>{{ r }}</p>
              {% if live_race == r.id %}
              {% if r.start_time == 0 %}
              <p style="margin: 13 13 13 13" id="count_down_p"></p>
              <script>

function getCookie(name) {
  let cookieValue = null;
  if (document.cookie && document.cookie !== "") {
    const cookies = document.cookie.split(";");
    for (let i = 0; i < cookies.length; i++) {
      const cookie = cookies[i].trim();
      // Does this cookie string begin with the name we want?
      if (cookie.substring(0, name.length + 1) === (name + "=")) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}

function getResults(onData) {
fetch("/tourneys/race_result", {
  method: "POST",
  credentials: "same-origin",
  headers: {
    "X-Requested-With": "XMLHttpRequest",
    "X-CSRFToken": getCookie("csrftoken"),
  },
  body: JSON.stringify({raceid: "{{r.id}}"})
})
.then(response => response.json())
.then(data => {
  if (onData) {
     onData(data);
  }
});
}

// Set the date we're counting down to
var wait_for = 15;
document.getElementById("count_down_p").innerHTML = wait_for;

// Update the count down every 1 second
var x = setInterval(function() {

  if (wait_for > 0) {
     wait_for = wait_for - 1;
     document.getElementById("count_down_p").innerHTML = wait_for;
  }
  else {
     document.getElementById("count_down_p").innerHTML = "GO!";
     clearInterval(x);
     var y = setInterval(function() {
       getResults(function(data) {
          console.log(data);
          if (data.start_time > 0) {
             clearInterval(y);
             //location.reload();
             window.location.href = "{% url 'tourneyz:run' tourney.id %}"; 
          }
       });
    }, 1000);
  }
}, 1000);

</script>
              {% endif %}
              {% endif %}
              {% if next_race == r.id %}
              <form action="#" method="get" style="margin: 13 13 13 13">
                 <input type="hidden" value="{{r.id}}" name="raceid" id="raceid" size="1" />
                 <input type="submit" class="btn" value="Start Race" name="startracebtn" id="startracebtn">
              </form>
              {% elif r.start_time > 0 %}
              {% localtime on %}
              <p>: Started at {{r.time_of_start}} <a href="{% url 'tourneyz:run' tourney.id %}">Refresh</a></p>
              {% endlocaltime %}
              {% endif %}
           </div>
        </li>
        <ol>
        {% for c in r.trials %}
        <li>{{ c }}</li>
        {% endfor %}
        </ol>
    {% endfor %}
    </ul>

{% else %}
    <p>There are NO races generated for this event.  Oops :(</p>
{% endif %}

{% else %}
    <p>There are no cars registered for this event.  <a href="{% url 'tourneyz:edit' tourney.id %}">Please add some racers!.</a></p>
{% endif %}