chrace/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('racers/', include('racers.urls')),
    path('tourneys/', include('tourneys.urls')),
    path('admin/', admin.site.urls),
]

racers/urls.py
from django.urls import path

from . import views

app_name = 'racerz'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/races/', views.DetailView.as_view(), name='races'),
    path('<int:pk>/times/', views.ResultsView.as_view(), name='times'),
]

racers/models.py
from django.db import models
from django.utils import timezone

# this represents the human "driving" the car
class Driver(models.Model):
   first_name = models.CharField(max_length=32)
   last_name = models.CharField(max_length=32)
   birthday = models.DateField()

   # the driver's age (as of today)
   def age(self):
      today = timezone.now()
      dob = self.birthday
      years = today.year - dob.year
      if today.month < dob.month or (today.month == dob.month and today.day < dob.day):
        years -= 1
      return years


   # a better way to represent drivers
   def __str__(self):
      age = self.age()
      agestr = f'{self.age()}yo'
      if age > 17:
         agestr = 'Adult'
      elif age > 12:
         agestr = 'Teen'
      return f'{self.first_name.capitalize()} {self.last_name.capitalize()} ({agestr})'

# this represents a single created car
class RaceCar(models.Model):
   driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
   name = models.CharField(max_length=64)

   def __str__(self):
      return self.name

racers/views.py
from django.shortcuts import get_object_or_404,render
from .models import Driver,RaceCar
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

class IndexView(generic.ListView):
   template_name = 'racers/index.html'
   context_object_name = 'all_cars'

   def get_queryset(self):
      return RaceCar.objects.all()

class DetailView(generic.DetailView):
   model = Driver
   template_name = 'racers/races.html'

class ResultsView(generic.DetailView):
   model = RaceCar
   template_name = 'racers/times.html'

def index(request):
   all_cars = RaceCar.objects.all()
   context = {'all_cars': all_cars}
   return render(request, 'racers/index.html', context)

def races(request, driver_id):
   driver = get_object_or_404(Driver, pk=driver_id)
   return render(request, 'racers/races.html', {'driver': driver})

def times(request, car_id):
   car = get_object_or_404(RaceCar, pk=car_id)
   return render(request, 'racers/times.html', {'car': car})

racers/templates/racers/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'racers/style.css' %}">

{% if all_cars %}
    <ul>
    {% for car in all_cars %}
        <li><a href="{% url 'racerz:times' car.id %}">
        <div class="card">
           <img src="{% static 'racers/images/boogers.png' %}" alt="Avatar" style="height:100px">
           <div class="container">
    <h4><b>{{ car.name }}</b></h4>
    <p>{{ car.driver.first_name }}</p>
  </div>
</div>
        </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Show all Racers here.</p>
{% endif %}

racers/templates/racers/races.html
<h1>Upcoming Tournaments for {{object}}</h1>

<h1>Past Tournaments for {{object}}</h1>

racers/templates/racers/times.html
<h1>Race Times for {{object}}</h1>

<p>This page should show the track times for {{ object }} (Race Car {{object.id}})</p>